name: Markdown Lint
on:
  pull_request:
    branches: [main]
jobs:
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          command: config
          globs: |
            .github/.markdownlint.json
            **/*.md
